# Generated by Django 3.0.6 on 2020-10-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='sku',
        ),
    ]
