# Generated by Django 3.0.6 on 2020-09-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
